- ext/tiny_tds/client.c
Starting with Ruby-2.2 strings can not be expected to be zero terminated.
It is therefore required to retrive String objets per StringValueCStr(). See https://github.com/ruby/ruby/blob/v2_2_0/NEWS#L319
Using StringValuePtr() without RSTRING_LEN() can lead to weird errors like:
http://stackoverflow.com/questions/28891447/weird-bytes-added-to-attribute-after-save-in-rails
> Ensure zero terminated strings, where C-str pointers are expected.

- lib/tiny_tds.rb
Ruby-1.9 did use a mix of DL and Fiddle. That's why commit 3c90660598 broke compat with Ruby-1.9, when running on a Unix system with builtin FreeTDS.
> Fix compat with Ruby <2.0.

- ext/tiny_tds/client.h
- ext/tiny_tds/result.c
- ext/tiny_tds/tiny_tds_ext.h
This is an alternate implementation of #217, with some slightly more
minimal changes. I didn't feel the need to move out the error code into
a separate file, and just forward declared the functions in the location
they were already at.
I'm a little concerned at the change from `char **` to `char *`, as that
code should have done horribly incorrect things if those pointers were
ever used previously. Everything else is pretty straightforward, just
missing some forward declarations and using the correct pointer casts
(pointer casting doesn't actually affect anything other than making the
compiler hush).
> Fix compiler warnings

- appveyor.yml
Takes advantage of Appyveor encrypted ENV vars. Even obfuscated the host just in case. We may have to get @larskanis PR of #224 in first for this to work.
> Allow CI to use SQL Azure. 

- test/client_test.rb
- test/result_test.rb
- test/test_helper.rb
- test/thread_test.rb
When upgrading to newer FreeTDS versions, we should really make sure we are not crossing the streams when testing and close every client connection we create.
> Make sure to close all test connections.

- .gitignore
- CHANGELOG
- README.md
- bin/tsql
- ext/tiny_tds/extconf.rb
- tiny_tds.gemspec
See #227 for full details.
* Copy `tsql` exe during FreeTDS compile install.
* Use ptools gem dep for easy cross platform `File.which` support.
* Local binstub will prefer local gem exe but delegate to system as needed.
> Local ruby binstubs `./bin/tsql` for `./exe/tsql` executable.

- Rakefile
- ext/tiny_tds/extconf.rb
- tiny_tds.gemspec
This should fix https://github.com/rails-sqlserver/tiny_tds/issues/252 . 
I was able to reproduce the "undefined method `include?' for nil:NilClass" error in #252 . But after the update to mini_portile2 it magically disappeared and `rake gem:windows` works fine now.
As a side note: rake-compiler-dock-0.5.0 will support ruby-2.3 as well. I'll release it when ruby-2.3.0 is released, so that binary gems can be built.
> Update to mini_portile2 and fix packaging of freetds tar as bz2.

- Rakefile
- tiny_tds.gemspec
I haven't actually tested it, so this PR is really to start the discussion. Are there blockers to cross compiling for 2.3?
> Add ruby 2.3 to the cross compile task

- lib/tiny_tds/client.rb
Allows for numeric options in URI connection strings. 
E.g. `tinytds://user:passwd@host:1433/database?timeout=60`
> Ensures numeric options are treated numerically

- README.md
- ext/tiny_tds/client.c
Allows support for contained users in recent SQL Server versions.
Running the specs from OS X against SQL Server 2016 (on remote windows server obviously)
renders one test failure, however the same failure is also present on `master`:
```
Basic query and result#test_0015_must insert and find unicode data [/Users/lowe/src/tiny_tds/test/result_test.rb:131]:
```
It's probably important to run on appveyor etc to make sure we don't break compatibility with old SQL Server versions.
> Always set database name in login packet

- CHANGELOG
- appveyor.yml
- circle.yml
- test/bin/install-freetds-1.00.21.sh
- test/client_test.rb
- test/test_helper.rb
The goal here is to use Appveyor only for the following:
* Non-current SQL Server. Examples 2014 and 2012.
* Lastest Ruby 64-bit version.
All other things will be left to CircleCI. Primarily this includes:
* Testing all major-supported Ruby versions.
* Testing SQL Server Linux & Ubuntu.
> More CircleCI with Less Appveyor

- ext/tiny_tds/client.c
- lib/tiny_tds/client.rb
||= is a deceiving operator for Boolean values. It could mean, assign-if-nil or assign-if-false. It is just a short-hand for `a = a || new_value`
> Don't reset use_utf16 option, when initializing with false

- .travis.yml
- appveyor.yml
- test/bin/install-freetds.sh
- test/bin/install-openssl.sh
- test/bin/setup.sh
A series of commits to see a) how to use TravisCI with docker and b) how the speed compares to CircleCI. Changes also include: 
* Reducing merge builds in both TravisCI & Appveyor.
* Update build scripts for OpenSSL & FreeTDS to do cleanup.
> More CI is better CI. Try TravisCI.

- .gitattributes
- Rakefile
- ext/tiny_tds/extconf.rb
- ext/tiny_tds/extconsts.rb
- ports/patches/freetds/1.00.27/0001-mingw_missing_inet_pton.diff
- test/bin/install-openssl.sh
See discussion on https://github.com/rails-sqlserver/tiny_tds/issues/310 and previous PR https://github.com/rails-sqlserver/tiny_tds/pull/344 by @metaskills.
> Openssl 1.1.0

- ext/tiny_tds/extconf.rb
This commit adds support for the FREETDS_DIR environment variable as an
alternative to configuring the freetds path via bundle config. This
eases configuration in environments like Heroku where configuration via
bundle config just isn't possible. This fixes a likely regression
caused by the miniportile build refactor.
Relates to issue #371
> Support the FREETDS_DIR environment variable

- README.md
- ext/tiny_tds/client.c
As referenced in an old issue (https://github.com/rails-sqlserver/tiny_tds/issues/84), TinyTDS currently only supports a single, global timeout value because of a limitation in FreeTDS. However, support for per-connection timeout values has been added to FreeTDS in the meantime (https://github.com/FreeTDS/freetds/commit/33fa016ca933ea5534007bce69c10e657e92e653), so we can take advantage of it now.
For some reason the call to FreeTDS expects a string value instead of an integer, so I'm forcing the conversion. This way it remains backward compatible with existing code.
> Add support for separate timeout values per connection

- ext/tiny_tds/client.c
- ext/tiny_tds/client.h
- ext/tiny_tds/result.c
- lib/tiny_tds/client.rb
- test/client_test.rb
- test/result_test.rb
- test/test_helper.rb
I work on a codebase that makes extensive use of info messages (eg, raiserror with a serverity level <= 10, such as `raiserror('hello world', 10 -1)`). I need to receive these info messages in ruby code, but until now TinyTds did not expose an API for this.
See updated iteration below
<details>
I have improved TinyTDS's to handle info messages, and introduced an experimental API to expose messages to users. This PR includes an improvement to the C code that handles errors with severity <= 10, and Ruby code that exposes messages to users.
The current philosophy of this project is to handle messages like errors. This PR does not change that perspective. Info messages are simply instances of `TinyTDS::Error`s but instead of throwing an exception, they're channeled through the new API. There …
> Info Messages

- README.md
- ext/tiny_tds/extconsts.rb
- test/bin/install-freetds.sh
This is related to #372 - The FreeTDS maintainers have officially added support for HTTP downloads.
> Use official HTTP mirrors instead of FTP

- README.md
Hi, today I was working on migrating `tiny_tds` to the latest stable version.
While doing so, I was following the README instructions and noticed a `tiny` error 😛  on the FreeTDS installation instructions.
Thanks!
> Fix FreeTDS installation instructions in README

- README.md
Closes #419
I removed documentation that said TinyTDS would install FreeTDS for you since that seems to have been removed in version 2. I can remove that change if it's unwanted.
> Add documentation about linking in Docker

- .travis.yml
- CHANGELOG.md
- README.md
- appveyor.yml
- ext/tiny_tds/extconf.rb
- ext/tiny_tds/extconsts.rb
- tasks/native_gem.rake
- tasks/ports.rake
- tasks/ports/openssl.rb
- tiny_tds.gemspec
This PR includes #455 . It adds ruby versions 2.6 and 2.7 to Windows binary gems and updates and fixes Appveyor and Travis CI. It also adds ruby-head to Appveyor-CI. It removes rubies before 2.4 and some necessary workarounds. OpenSSL and FreeTDS are updated to the latest release versions.
Appveyor needs to be re-enabled for this repository to be effective.
> Update cross build, Travis and Appveyor-CI

- .travis.yml
- CHANGELOG.md
- README.md
- tasks/native_gem.rake
This is a prerequisite for https://github.com/rails-sqlserver/tiny_tds/issues/434 (per [comment](https://github.com/rails-sqlserver/tiny_tds/issues/434#issuecomment-485863370)). It's effectively a followup to https://github.com/rails-sqlserver/tiny_tds/pull/428.
Adding recent contributors for review.
> Remove old Ruby version from CI config & cross build rake task

- CHANGELOG.md
- test/client_test.rb
- test/result_test.rb
- test/schema_test.rb
- test/thread_test.rb
Fixing a few test warnings:
```
test/result_test.rb:687: warning: assigned but unused variable - result1
test/schema_test.rb:17: warning: ambiguous first argument; put parentheses or a space even after `-' operator
test/schema_test.rb:99: warning: ambiguous first argument; put parentheses or a space even after `-' operator
test/schema_test.rb:173: warning: ambiguous first argument; put parentheses or a space even after `-' operator
test/schema_test.rb:407: warning: ambiguous first argument; put parentheses or a space even after `-' operator
test/thread_test.rb:52: warning: assigned but unused variable - e
```
> Fix test warnings

- README.md
The Dependency Status badge no longer works so removing from the README.
> Remove dependency status badge

- appveyor.yml
AppVeyor builds have been failing during `freetds` installation due to outdated packages:
```
warning: no /var/cache/pacman/pkg/ cache exists, creating...
error: failed retrieving file 'mingw-w64-i686-freetds-1.00.100-1-any.pkg.tar.xz' from repo.msys2.org : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-i686-freetds-1.00.100-1-any.pkg.tar.xz' from sourceforge.net : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-i686-freetds-1.00.100-1-any.pkg.tar.xz' from www2.futureware.at : The requested URL returned error: 404
error: failed retrieving file 'mingw-w64-i686-freetds-1.00.100-1-any.pkg.tar.xz' from mirror.yandex.ru : The requested URL returned error: 404
warning: failed to retrieve some files
error: failed to commit …
```
> AppVeyor - Fix freetds install errors by updating packages

- appveyor.yml
Appveyor builds were failing when updating packages:
```
:: Proceed with installation? [Y/n] 
:: Retrieving packages...
downloading bash-5.1.004-1-x86_64.pkg.tar.zst...
downloading filesystem-2021.01-1-x86_64.pkg.tar.zst...
downloading mintty-1~3.4.4-1-x86_64.pkg.tar.zst...
downloading msys2-runtime-3.1.7-4-x86_64.pkg.tar.xz...
downloading msys2-runtime-devel-3.1.7-4-x86_64.pkg.tar.xz...
downloading pacman-mirrors-20201208-1-any.pkg.tar.xz...
downloading zstd-1.4.8-1-x86_64.pkg.tar.zst...
downloading pacman-5.2.2-9-x86_64.pkg.tar.zst...
checking keyring...
checking package integrity...
loading package files...
error: could not open file /var/cache/pacman/pkg/bash-5.1.004-1-x86_64.pkg.tar.zst: Child process exited with status 127
error: could not open file …
```
> Fix appveyor builds with pacman update workaround

- appveyor.yml
Appveyor builds were breaking due to an error related to pacman when running `bundle install`:
```
warning: database file for 'ucrt64' does not exist (use '-Sy' to download)
warning: database file for 'clang64' does not exist (use '-Sy' to download)
error: failed to prepare transaction (could not find database)
```
Running `pacman --noconfirm -Sy` to update the package list resolves this error and the builds pass successfully.
> Fix Appveyor builds by refreshing the package list

- .travis.yml
- CHANGELOG.md
- README.md
- docker-compose.yml
- ext/tiny_tds/client.c
- ext/tiny_tds/result.c
- test/client_test.rb
- test/test_helper.rb
- tiny_tds.gemspec
In cases of network failure with a command batch running - configured timeouts were not being respected. This meant that the time elapsed before a `TinyTds::Error` was thrown would extend well beyond the configured timeout #445.
The reason for this is due to the fact that `dbcancel` does not work under these conditions. The `tinytds_err_handler` is called when the timeout is reached, we return `INT_TIMEOUT` and attempt to cancel the command batch using `dbcancel`. That call fails which means we continue to wait for the command batch to return even when subsequent timeout errors are reported.
Ideally to fix this we would detect if `dbcancel` fails and return `INT_CANCEL` in these circumstances. Unfortunately, we can't do this given that `dbcancel` [will always return …
> Improve handling of network related timeouts

- CHANGELOG.md
- ext/tiny_tds/client.c
- ext/tiny_tds/client.h
- ext/tiny_tds/result.c
- test/result_test.rb
- test/test_helper.rb
Capturing errors while in a non-blocking state was originally structured to capture a single error. This was intentional in order to avoid capturing more generic info messages that FreeTDS might send before the Global VM Lock was obtained. In most circumstances this is what we want. However, now that we capture info messages it is possible that a info message will be stored and the actual runtime error will be mistakenly discarded as non-important. The result is that while a runtime error is reported in the database, a `TinyTds` error is never thrown and only the info message is handled. A subset of this problem is that only one info message can be captured while in non-blocking mode which prevents stored procedures from reporting multiple info messages to `TinyTds`.
To fix this issue, …
> Report stored procedure errors when using info messages

- CHANGELOG.md
- ext/tiny_tds/result.c
> Fix for loop initial declarations C99 error

- CHANGELOG.md
- ext/tiny_tds/client.c
- test/client_test.rb
Fixes a bug introduced in #481. When a login timeout occurs, `userdata` has not been initialized so it is a null pointer. Updating the timeout error handling to detect this so no segmentation fault occurs. Added a test to ensure login timeouts are working as expected.
> Fix login timeout segmentation faults

- .circleci/config.yml
- CHANGELOG.md
- Rakefile
Replaces #524 
This PR adds Ruby 3.0 to the cross-compile list. With #525, few things related to the CI changed and couple of changes like the OpenSSL update have been implemented with #525 as well. So opening a new PR was simpler than overwriting the existing one.
> Add Ruby 3.0 to the cross compile list

- CHANGELOG.md
- ext/tiny_tds/client.c
- test/client_test.rb
Hey there!
Firstly, I want to express my appreciation for the hard work and dedication that you have put into maintaining this project. Your efforts have been incredibly valuable to me and many others in the community.
Well, as reported in the issue #519, we ran into an unexpected Segmentation Fault Error while verifying whether a client was dead after closing it. Upon investigation, we discovered (following the [leads](https://github.com/rails-sqlserver/tiny_tds/issues/519#issuecomment-1222718722) of @aharpervc ) that the root cause of the issue was that by calling `dbclose`, we were [deallocating memory used by the client structure without setting the pointer to NULL](https://github.com/FreeTDS/freetds/blob/0a87ec6faf26c187ed58fb52ddf070b445bfbec9/src/dblib/dblib.c#L1541) after closing …
> Fix dangling pointer after client.close

- CHANGELOG.md
- ext/tiny_tds/result.c
From my understanding, you only need to define an `alloc` function if you want to define a C struct and store values on it. For example, `TinyTds::Client` defines such an `allocate` function to wrap its client. On `TinyTds::Result`, it does not seem we do have a struct and therefore does not need an `alloc` function.
Closes #515
> Mark `alloc` as undefined for `TinyTds::Result`

- .circleci/config.yml
As I parallelized the cross-compilation process, the gems were moved into another folder dedicated to their target platform during the build. This change was not reflected when storing the artifacts.
> Fix path to artifacts

- .circleci/config.yml
I observed that sometimes, CircleCI hangs for a solid 10 minutes on the "Ruby diagnostic" step. Perl, Ruby and Gem version are already visible, so I assume that the delete operation takes very long sometimes.
I do no think we need to throw away the setup file ourselves, as we get fresh VMs with each run anyhow. However, CircleCI does not like if the current directory, where you want to check out the code, is not empty. Downloading the setup file to C: should fix that issue.
> Do not remove Ruby setup file

- .circleci/config.yml
On the corresponding PR (https://github.com/rails-sqlserver/tiny_tds/pull/545), everything looked fine and the build passed: https://app.circleci.com/pipelines/github/andyundso/tiny_tds/55/workflows/727c3150-0a8f-40a7-8a5f-9fd58e4e9428
However, once merged to master, the build failed since the executor was not available for the `tiny_tds` organization (see https://app.circleci.com/pipelines/github/rails-sqlserver/tiny_tds/18/workflows/47a0e21f-eda7-4901-a34b-ca4265f4f344/jobs/486). Although it would be helpful to have it, this commit removes the Apple Silicon build on CircleCI.
> Remove Apple Silicon build on CircleCI

- .circleci/config.yml
- CHANGELOG.md
- Rakefile
- tiny_tds.gemspec
I assume the `activerecord-sql-adapter` is the source of most of our Gem installations. Rails 7.0 requires Ruby 2.7 at minimum. I think this a good base line for now. It would still allow people with older Rubys to upgrade to the eventual v3.0 release, but we do no longer support ancient Ruby versions (like 2.4).
Related to #552.
> Drop support for Ruby < 2.7

- CHANGELOG.md
- ext/tiny_tds/client.c
Closes #464
Relates to #552
With this PR, `tiny_tds` will raise an error in case `dbsqlsend` will return `FAIL` instead of returning false. It is essentially the code from #469 / @wpolicarpo.
I spent an evening trying to build a test that would yield this error. I came up with a solution that worked on my machine, but only sometimes on CI.
```ruby
it 'raises error when query cannot be sent' do
client = new_connection
assert_client_works(client)
thread1 = Thread.new do
client.execute("SELECT 1 as [one]").do
end
thread2 = Thread.new do
assert_equal false, client.execute("SELECT 1 as [one]")
end
thread1.join
thread2.join
end
```
I assume, when the result are read in thread1 and Ruby decides to switch to thread2, our FreeTDS wrapper is in an invalid state, which can trigger the issue. Likely, …
> Raise error if dbsqlsend fails

- .github/workflows/ci.yml
Microsoft SQL Server 2017 will not work on Ubuntu 24.04.
> Pin CI to Ubuntu 22.04

- .github/workflows/ci.yml
- tiny_tds.gemspec
This is to address the following warning on Ruby 3.3:
```
/home/apf/dev/rails-sqlserver/tiny_tds/lib/tiny_tds.rb:3: warning: bigdecimal was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add bigdecimal to your Gemfile or gemspec.
```
> Add `bigdecimal` as a dependency

- README.md
Closes #447
I quickly tested setting the TDS version manually on client initialization and it seems to work as expected. `tds_version` is implemented in C and asks the `dbproc` struct about the used version, so this information should be reliable.
```
irb(main):001> require "tiny_tds"
=> true
irb(main):002* client = TinyTds::Client.new({
irb(main):003*     username: "tinytds",
irb(main):004*     password: "",
irb(main):005*     host: "127.0.0.1",
irb(main):006*     tds_version: "7.3"
irb(main):007> })
=> 
#<TinyTds::Client:0x0000767d1cb58f00
...
irb(main):008> client.tds_version
=> 11
irb(main):009* client = TinyTds::Client.new({
irb(main):010*     username: "tinytds",
irb(main):011*     password: "",
irb(main):012*     host: "127.0.0.1",
irb(main):013*     tds_version: "7.4" …
```
> Remove information in README about issues with TDS version at login
